spring.application.name=demo
#server.port = 8081

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://109.198.190.115:32322/BadanovA
spring.datasource.username=student
spring.datasource.password=5432

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

# ????????? Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML5

# ????????? ?????? ?????? Spring Boot
spring.servlet.multipart.max-file-size=-1
spring.servlet.multipart.max-request-size=-1

spring.jpa.show-sql=true
logging.level.sql=debug
